default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: login_app_development
  
test:
  <<: *default
  database: login_app_test
  
production:
  <<: *default
  database: login_app_production
  username: login_app
  password: <%= ENV['LOGIN_APP_DATABASE_PASSWORD'] %>